SET SEARCH_PATH TO WFA;
--1
SELECT * FROM ACCOMMODATION WHERE (CITY='Jaipur');
--2
SELECT Accommodation_Name,ROOM_TYPE.* FROM (ACCOMMODATION NATURAL JOIN ROOM_TYPE) 
	WHERE (CITY='Jaipur');
--3
SELECT Accommodation_Name,Room_Type_Name,ACCOMMODATION_FARES.*
	FROM (ACCOMMODATION NATURAL JOIN ROOM_TYPE NATURAL JOIN ACCOMMODATION_FARES) 
	WHERE (CITY='Jaipur');

SELECT COUNT(Accommodation_ID),CITY FROM ACCOMMODATION GROUP BY CITY;

--4
SELECT * FROM ACCOMMODATION
	WHERE CITY='Shimla' AND STARTING_PRICE<1000;

--5

SELECT T.TRANSPORTATION_NAME,T.USER_RATING,T.Transportation_Type,R.* FROM TRANSPORTATION AS T
NATURAL JOIN
	(SELECT S.TRANSPORTATION_ID, S.STATION_CODE, S.ARRIVAL AS S_ARRIVAL, S.DEPARTURE AS S_DEPARTURE, S.HALT AS S_HALT,S.DAY_NO AS S_DAY_NO, 
	 D.STATION_CODE, D.ARRIVAL AS D_ARRIVAL, D.DEPARTURE AS D_DEPARTURE , D.HALT AS D_HALT,D.DAY_NO AS D_DAY_NO FROM 
		(SELECT ROUTE.* FROM ROUTE NATURAL JOIN (SELECT * FROM STATION WHERE CITY='Navsari') AS N) AS S
 		JOIN 
		(SELECT ROUTE.* FROM ROUTE NATURAL JOIN (SELECT * FROM STATION WHERE CITY='Ahmedabad ') AS A) AS D ON S.TRANSPORTATION_ID=D.TRANSPORTATION_ID
	WHERE S.STOP_NUMBER < D.STOP_NUMBER) AS R;
	
	
--6
SELECT P.*,TC.CLASS_NAME FROM
(SELECT T.TRANSPORTATION_NAME,T.USER_RATING,R.* FROM TRANSPORTATION AS T
NATURAL JOIN
	(SELECT S.TRANSPORTATION_ID, S.STATION_CODE, S.ARRIVAL AS S_ARRIVAL, S.DEPARTURE AS S_DEPARTURE, S.HALT AS S_HALT,S.DAY_NO AS S_DAY_NO, S.KM_FROM_ORIGIN AS S_KM_FROM_ORIGIN,
	 D.STATION_CODE, D.ARRIVAL AS D_ARRIVAL, D.DEPARTURE AS D_DEPARTURE , D.HALT AS D_HALT,D.DAY_NO AS D_DAY_NO,D.KM_FROM_ORIGIN AS D_KM_FROM_ORIGIN FROM 
		(SELECT * FROM ROUTE NATURAL JOIN (SELECT * FROM STATION WHERE CITY='Navsari') AS N) AS S
 		JOIN 
		(SELECT * FROM ROUTE NATURAL JOIN (SELECT * FROM STATION WHERE CITY='Ahmedabad ') AS A) AS D ON S.TRANSPORTATION_ID=D.TRANSPORTATION_ID
	WHERE S.STOP_NUMBER < D.STOP_NUMBER) AS R ) AS P
	NATURAL JOIN 
	(TRANSPORTATION_CLASS NATURAL JOIN CLASSES) AS TC;
	
	
--7
SELECT PP.*,(D_KM_FROM_ORIGIN-S_KM_FROM_ORIGIN)*BASE_PRICE AS BASE_PRICE,(D_KM_FROM_ORIGIN-S_KM_FROM_ORIGIN)*TAXES AS TAXES,
TF.BREAKFAST,TF.LUNCH,TF.DINNER,TF.ZERO_CANCELLATION FROM
(SELECT P.*,TC.CLASS_NAME FROM
(SELECT T.TRANSPORTATION_NAME,T.USER_RATING,R.* FROM TRANSPORTATION AS T
NATURAL JOIN
	(SELECT S.TRANSPORTATION_ID, S.STATION_CODE, S.ARRIVAL AS S_ARRIVAL, S.DEPARTURE AS S_DEPARTURE, S.HALT AS S_HALT,S.DAY_NO AS S_DAY_NO, S.KM_FROM_ORIGIN AS S_KM_FROM_ORIGIN,
	 D.STATION_CODE, D.ARRIVAL AS D_ARRIVAL, D.DEPARTURE AS D_DEPARTURE , D.HALT AS D_HALT,D.DAY_NO AS D_DAY_NO,D.KM_FROM_ORIGIN AS D_KM_FROM_ORIGIN FROM 
		(SELECT * FROM ROUTE NATURAL JOIN (SELECT * FROM STATION WHERE CITY='Navsari') AS A) AS S
 		JOIN 
		(SELECT * FROM ROUTE NATURAL JOIN (SELECT * FROM STATION WHERE CITY='Ahmedabad ') AS A) AS D ON S.TRANSPORTATION_ID=D.TRANSPORTATION_ID
	WHERE S.STOP_NUMBER < D.STOP_NUMBER) AS R ) AS P
	NATURAL JOIN 
	(TRANSPORTATION_CLASS NATURAL JOIN CLASSES) AS TC) AS PP
	NATURAL JOIN
	TRANSPORTATION_FARES AS TF 
	;
	
--AVAILABLE SEATS
SELECT TRANSPORTATION_NAME,CLASS_NAME,AVL.* FROM
(SELECT P.*,TC.CLASS_NAME,TC.CLASS_ID FROM
(SELECT T.TRANSPORTATION_NAME,T.USER_RATING,R.* FROM TRANSPORTATION AS T
NATURAL JOIN
	(SELECT S.TRANSPORTATION_ID, S.STATION_CODE, S.ARRIVAL AS S_ARRIVAL, S.DEPARTURE AS S_DEPARTURE, S.HALT AS S_HALT,S.DAY_NO AS S_DAY_NO, S.KM_FROM_ORIGIN AS S_KM_FROM_ORIGIN,
	 D.STATION_CODE, D.ARRIVAL AS D_ARRIVAL, D.DEPARTURE AS D_DEPARTURE , D.HALT AS D_HALT,D.DAY_NO AS D_DAY_NO,D.KM_FROM_ORIGIN AS D_KM_FROM_ORIGIN FROM 
		(SELECT * FROM ROUTE NATURAL JOIN (SELECT * FROM STATION WHERE CITY='Jaipur') AS N) AS S
 		JOIN 
		(SELECT * FROM ROUTE NATURAL JOIN (SELECT * FROM STATION WHERE CITY='Jodhpur') AS A) AS D ON S.TRANSPORTATION_ID=D.TRANSPORTATION_ID
	WHERE S.STOP_NUMBER < D.STOP_NUMBER) AS R ) AS P
	NATURAL JOIN 
	(TRANSPORTATION_CLASS NATURAL JOIN CLASSES) AS TC) AS F
	JOIN AVAILABLE_SEATS AS AVL ON (AVL.TRANSPORTATION_ID=F.TRANSPORTATION_ID AND AVL.CLASS_ID=F.CLASS_ID) WHERE DEPARTURE_TIMESTAMP BETWEEN '2023-05-16 06:00:00' AND '2023-05-23 06:00:00';
	
-- SELECT OFFER_ID,PACKAGE_ID, SUM(BASE_PRICES) FROM 
-- (SELECT OFFER_ID, PACKAGE_ID, ACCOMMODATION_ID, SUM(BASE_PRICE*DAYS)/2 AS BASE_PRICES 
-- FROM OFFER_ACCOMMODATION 
-- NATURAL JOIN ACCOMMODATION_FARES 
-- GROUP BY OFFER_ID, PACKAGE_ID,ACCOMMODATION_ID) AS BP GROUP BY OFFER_ID, PACKAGE_ID;

--8
SELECT * FROM
(SELECT BOOKING_ID FROM BOOKING
EXCEPT
SELECT BACKEND_BOOKING_ID FROM PACKAGE_BOOKING_DETAILS) AS AB
NATURAL JOIN ACCOMMODATION_BOOKING;

--
SELECT CD.*,INVOICE_ID FROM
(SELECT * FROM
(SELECT BOOKING_ID FROM BOOKING
EXCEPT
SELECT BACKEND_BOOKING_ID FROM PACKAGE_BOOKING_DETAILS) AS AB
NATURAL JOIN ACCOMMODATION_BOOKING) AS CD
NATURAL JOIN BOOKING
;
--
CREATE VIEW O_ACCM_B AS  
SELECT CD.*,INVOICE_ID FROM
(SELECT * FROM
(SELECT BOOKING_ID FROM BOOKING
EXCEPT
SELECT BACKEND_BOOKING_ID FROM PACKAGE_BOOKING_DETAILS) AS AB
NATURAL JOIN ACCOMMODATION_BOOKING) AS CD
NATURAL JOIN BOOKING
;
--
SELECT * FROM O_ACCM_B ;
--
SELECT * FROM 
(SELECT * FROM O_ACCM_B 
NATURAL JOIN ACCOMMODATION_FARES) AS AF 
 JOIN ACCOMMODATION_ADD_ON AS AD ON (AF.BOOKING_ID=AD.BOOKING_ID) 
 ;
 --
SELECT INVOICE_ID,AF.BASE_PRICE,
 (AF.BREAKFAST*AD.BREAKFAST)AS BREAKFAST,
 (AF.LUNCH_OR_DINNER*AD.LUNCH_OR_DINNER) AS LUNCH_OR_DINNER,
 (AF.LUNCH_AND_DINNER*AD.DINNER) AS DINNER,
 (AF.ZERO_CANCELLATION*AD.ZERO_CANCELLATION) AS ZERO_CANCELLATION,
  (AF.Mattresses*AD.No_Of_Mattresses) AS Mattresses,
 AF.TAXES FROM 
(SELECT * FROM O_ACCM_B 
NATURAL JOIN ACCOMMODATION_FARES) AS AF 
 JOIN ACCOMMODATION_ADD_ON AS AD ON (AF.BOOKING_ID=AD.BOOKING_ID) 
 ;
 --
SELECT INVOICE_ID,(F.Mattresses+F.BASE_PRICE+F.BREAKFAST + F.LUNCH_OR_DINNER + F.DINNER + F.ZERO_CANCELLATION) AS TOTAL ,TAXES FROM
(SELECT INVOICE_ID,AF.BASE_PRICE,
 (AF.BREAKFAST*AD.BREAKFAST)AS BREAKFAST,
 (AF.LUNCH_OR_DINNER*AD.LUNCH_OR_DINNER) AS LUNCH_OR_DINNER,
 (AF.LUNCH_AND_DINNER*AD.DINNER) AS DINNER,
 (AF.ZERO_CANCELLATION*AD.ZERO_CANCELLATION) AS ZERO_CANCELLATION,
  (AF.Mattresses*AD.No_Of_Mattresses) AS Mattresses,
 AF.TAXES FROM 
(SELECT * FROM O_ACCM_B 
NATURAL JOIN ACCOMMODATION_FARES) AS AF 
 JOIN ACCOMMODATION_ADD_ON AS AD ON (AF.BOOKING_ID=AD.BOOKING_ID) ) AS F
 ;
 
--10
SELECT *,(FF.TOTAL+ FF.TAXES) AS GRAND_TOTAL FROM 
(SELECT INVOICE_ID,(F.Mattresses+F.BASE_PRICE+F.BREAKFAST + F.LUNCH_OR_DINNER + F.DINNER + F.ZERO_CANCELLATION) AS TOTAL ,TAXES FROM
(SELECT INVOICE_ID,AF.BASE_PRICE,
 (AF.BREAKFAST*AD.BREAKFAST)AS BREAKFAST,
 (AF.LUNCH_OR_DINNER*AD.LUNCH_OR_DINNER) AS LUNCH_OR_DINNER,
 (AF.LUNCH_AND_DINNER*AD.DINNER) AS DINNER,
 (AF.ZERO_CANCELLATION*AD.ZERO_CANCELLATION) AS ZERO_CANCELLATION,
  (AF.Mattresses*AD.No_Of_Mattresses) AS Mattresses,
 AF.TAXES FROM 
(SELECT * FROM O_ACCM_B 
NATURAL JOIN ACCOMMODATION_FARES) AS AF 
 JOIN ACCOMMODATION_ADD_ON AS AD ON (AF.BOOKING_ID=AD.BOOKING_ID) ) AS F) AS FF
 ;
 
 --11
 SELECT * FROM
(SELECT BOOKING_ID FROM BOOKING
EXCEPT
SELECT BACKEND_BOOKING_ID FROM PACKAGE_BOOKING_DETAILS) AS AB
NATURAL JOIN TRANSPORTATION_BOOKING;
 
--
SELECT CD.*,INVOICE_ID FROM
(SELECT * FROM
(SELECT BOOKING_ID FROM BOOKING
EXCEPT
SELECT BACKEND_BOOKING_ID FROM PACKAGE_BOOKING_DETAILS) AS AB
NATURAL JOIN TRANSPORTATION_BOOKING) AS CD
NATURAL JOIN BOOKING;
 
 --
 CREATE VIEW O_TRANS_B AS  
SELECT CD.*,INVOICE_ID FROM
(SELECT * FROM
(SELECT BOOKING_ID FROM BOOKING
EXCEPT
SELECT BACKEND_BOOKING_ID FROM PACKAGE_BOOKING_DETAILS) AS AB
NATURAL JOIN TRANSPORTATION_BOOKING) AS CD
NATURAL JOIN BOOKING
;
--
SELECT * FROM O_TRANS_B ;
--
CREATE VIEW RFB AS
SELECT BOOKING_ID,R.TRANSPORTATION_ID,CLASS_ID,FROM_STATION,INVOICE_ID,stop_number AS FROM_stop_no,km_from_origin AS FROM_km
FROM (SELECT BOOKING_ID,TRANSPORTATION_ID,CLASS_ID,FROM_STATION,INVOICE_ID FROM O_TRANS_B) AS OTBF
JOIN
(SELECT * FROM ROUTE) AS R
ON (OTBF.TRANSPORTATION_ID = R.TRANSPORTATION_ID 
AND OTBF.FROM_STATION = R.STATION_CODE);
--
CREATE VIEW RTB AS
SELECT BOOKING_ID,R.TRANSPORTATION_ID,CLASS_ID,TO_STATION,INVOICE_ID,stop_number AS TO_stop_no,km_from_origin AS TO_km
FROM (SELECT BOOKING_ID,TRANSPORTATION_ID,CLASS_ID,TO_STATION,INVOICE_ID FROM O_TRANS_B) AS OTBT
JOIN
(SELECT * FROM ROUTE) AS R
ON (OTBT.TRANSPORTATION_ID = R.TRANSPORTATION_ID 
AND OTBT.TO_STATION = R.STATION_CODE);


--
SELECT * FROM
((SELECT * FROM RTB 
NATURAL JOIN RFB) 
AS RTFB NATURAL JOIN TRANSPORTATION_FARES)
AS RTFB WHERE TO_stop_no>FROM_stop_no;

--

SELECT INVOICE_ID,((to_km-from_km)*PRTFB.BASE_PRICE) as BASE_PRICE,(PRTFB.BREAKFAST*TADD.BREAKFAST)AS BREAKFAST,
(PRTFB.LUNCH*TADD.LUNCH) AS LUNCH,
(PRTFB.DINNER*TADD.DINNER) AS DINNER,
(PRTFB.ZERO_CANCELLATION*TADD.ZERO_CANCELLATION) AS ZERO_CANCELLATION,
((to_km-from_km) * PRTFB.TAXES) AS TAXES FROM
(SELECT * FROM
((SELECT * FROM RTB 
NATURAL JOIN RFB) 
AS RTFB NATURAL JOIN TRANSPORTATION_FARES)
AS RTFB WHERE TO_stop_no>FROM_stop_no) 
AS PRTFB JOIN TRANSPORTATION_ADD_ON AS TADD ON TADD.BOOKING_ID = PRTFB.BOOKING_ID;
--
SELECT INVOICE_ID,(F.BASE_PRICE+F.BREAKFAST + F.LUNCH + F.DINNER + F.ZERO_CANCELLATION) AS TOTAL,F.TAXES FROM
(SELECT INVOICE_ID,((to_km-from_km)*PRTFB.BASE_PRICE) as BASE_PRICE,(PRTFB.BREAKFAST*TADD.BREAKFAST)AS BREAKFAST,
(PRTFB.LUNCH*TADD.LUNCH) AS LUNCH,
(PRTFB.DINNER*TADD.DINNER) AS DINNER,
(PRTFB.ZERO_CANCELLATION*TADD.ZERO_CANCELLATION) AS ZERO_CANCELLATION,
((to_km-from_km) * PRTFB.TAXES) AS TAXES FROM
(SELECT * FROM
((SELECT * FROM RTB 
NATURAL JOIN RFB) 
AS RTFB NATURAL JOIN TRANSPORTATION_FARES)
AS RTFB WHERE TO_stop_no>FROM_stop_no) 
AS PRTFB JOIN TRANSPORTATION_ADD_ON AS TADD ON TADD.BOOKING_ID = PRTFB.BOOKING_ID) AS F;

SELECT * FROM INVOICE_DETAILS;


SELECT AVAILABLE_ROOMS.* FROM AVAILABLE_ROOMS NATURAL JOIN ACCOMMODATION WHERE CITY='Manali';
